### ISSUE TITLE
Wrong type argument: commandp (Spacemacs)

### ISSUE THREAD

**Issue by prestancedesign** [dfeich/org-clock-convenience#3]
Hello,

I'm using Spacemacs, I have configured your snippet :
```lisp
(defun dfeich/org-agenda-mode-fn ()
  (define-key org-agenda-mode-map
    (kbd "<S-up>") #'org-clock-convenience-timestamp-up)
  (define-key org-agenda-mode-map
    (kbd "<S-down>") #'org-clock-convenience-timestamp-down)
  (define-key org-agenda-mode-map
    (kbd "ö") #'org-clock-convenience-fill-gap)
  (define-key org-agenda-mode-map
    (kbd "é") #'org-clock-convenience-fill-gap-both))
(add-hook 'org-agenda-mode-hook #'dfeich/org-agenda-mode-fn)
```
When I try to shift clock, I have this error :

`Wrong type argument: commandp, org-clock-convenience-timestamp-up`

Best regards.

**Comment by dfeich** [comment]
Hi

The error you get would usually point to Emacs expecting a function which can be called interactively, but what you are passing is not fullfilling that requirement. Now, `org-clock-convenience-timestamp-up` clearly is an interactive command. This leads me to the suspicion that the module is maybe not loaded.

You can check whether the command is available by using `C-h f org-clock-convenience-timestamp-up`. That should show you the help text, if it is loaded.

Or you can execute in the scratch buffer

    (featurep 'org-clock-convenience)

which should give true 't' only when the module has been loaded and the feature therefore is defined.

If it is not defined, load the module by doing

    (require 'org-clock-convenience)

I hope this helps

**Comment by prestancedesign** [comment]
Hi

You're right, the module was simply not loaded. :)

Spacemacs doesn't need `require` to load module https://github.com/syl20bnr/spacemacs/blob/master/doc/LAYERS.org#no-require but there is an exception for Org extensions visibly https://github.com/syl20bnr/spacemacs/issues/3895.

Thank you !

**Comment by prestancedesign** [comment]
And thank you for this module, nice works !
