### ISSUE TITLE
fill-gap and fill-gap-both don't work:

### ISSUE THREAD

**Issue by gautammohan** [dfeich/org-clock-convenience#5]
Hi,

I'm running into an issue after installing org-clock-convenience. When I try to use the fill-gap functions, the function does not work, producing an error message in the mini buffer:

`Symbol’s value as variable is void: org-ts-regexp-inactive`

The clock entries change in the agenda view, but the actual buffer is not update. Any idea what might be happening? Thanks in advance!

**Comment by dfeich** [comment]
Hi

`org-ts-regexp-inactive` is a variable set in the basic `org.el` of org mode. This may point to that you are using quite an old org-mode. This variable was added to org 4 years ago and I think all version of org > 8 should be covered by it.

Could you check your org-mode version by executing `M-x org-version`? and your emacs version `M-x emacs-version`. I've also seen cases where a package-update of org-mode has led to a "mixed" or corrupted version to be running (happened in earlier times often, if you carry out the update in an emacs where the old version of org is already active).

**Comment by dfeich** [comment]
Sorry, I inadvertently hit the close button of my laptop... I did not want to close your issue

**Comment by gautammohan** [comment]
Org mode version 9.1.14 (9.1.14-1-g4931fc-elpa @ /.../.emacs.d/elpa/org-9.1.14/)
GNU Emacs 25.3.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2017-09-12

I actually restarted emacs and it works fine now. I did do a package-update to install, which I think caused the issue. Thanks for getting back to me!
