### ISSUE TITLE
Can only edit some clocked time log lines

### ISSUE THREAD

**Issue by stefanavey** [dfeich/org-clock-convenience#6]
I can edit the clocked time log line (e.g. `org-clock-convenience-timestamp-down`) for only the 1st line in the agenda view.  It works for both hours and minutes but when I go to any other line, I get this error message in the minibuffer `Error: not on a clocked time log line`.

org-clock-convenience version: `20160830.1856`
cl-lib version: 1.0
Org mode version: 9.1.13
Emacs version: 26.1

**Comment by dfeich** [comment]
Hi. I am currently running on org 9.1.14 from MELPA which is even a bit newer than yours, and for me it still works fine. So, probably the error is not about a change in the agenda display causing an incompatibility. The error is triggered when the agenda line you are on, does not match the regexp in `org-clock-convenience-clocked-agenda-re`. Are you sure that you try it on a "Clocked:" time line and not on another log line, e.g. a line displaying a "Closed:" or other state change? Please put some examples of lines which do not work in your reply, then I can test why they do not match.

**Comment by stefanavey** [comment]
Ok, so I think I tracked down the issue to the file name.  Here are 2 test entries I made.  The first one works fine.  The 2nd one does not work.  You can see that the file name is so long that there is no space after the colon.

    test:       15:45-15:55 Clocked:   (0:10) Entry 1
    testlongfile:15:45-15:55 Clocked:   (0:10) Entry 1

I looked into `org-clock-convenience-clocked-agenda-re` as you suggested and 1 or more spaces are expected after the filename.

    "^ +\\([^:]+\\): +\\(\\([ 012][0-9]\\):\\([0-5][0-9]\\)\\)\\(?:-\\(\\([ 012][0-9]\\):\\([0-5][0-9]\\)\\)\\|.*\\)? +Clocked: +\\(([0-9]+:[0-5][0-9])\\|(-)\\)"

I can successfully modify both test entries after making the space optional by changing the 3rd `+` to `*`.

    "^ +\\([^:]+\\): *\\(\\([ 012][0-9]\\):\\([0-5][0-9]\\)\\)\\(?:-\\(\\([ 012][0-9]\\):\\([0-5][0-9]\\)\\)\\|.*\\)? +Clocked: +\\(([0-9]+:[0-5][0-9])\\|(-)\\)"

Any reason not to change this for everyone?

**Comment by dfeich** [comment]
Hi, that should be completely fine. I just implemented the change and committed with reference to this issue. Thank you for the report.
